---
- hosts: localhost
  vars_files: ../vars.yml
  tasks:

  - name: Register OPNsense image file
    ansible.builtin.stat:
      path: '{{ images_dir }}/{{ opnsense_image_file }}'
    register: opnsense_image_file_stat

  - name: Register OPNsense image archive file
    ansible.builtin.stat:
      path: '{{ images_dir }}/{{ opnsense_image_archive_file }}'
      checksum_algorithm: sha256
    register: opnsense_image_archive_file_stat

  - name: Download OPNsense image archive
    ansible.builtin.get_url:
      url: '{{ opnsense_image_url }}/{{ opnsense_image_archive_file }}'
      dest: '{{ images_dir }}/{{ opnsense_image_archive_file }}'
      checksum: 'sha256:{{ opnsense_image_archive_file_sha256 }}'
    when: opnsense_image_file_stat.stat.exists is false and opnsense_image_archive_file_stat.stat.exists is false

  - name: Extract OPNsense image archive
    ansible.builtin.shell:
      cmd: bzip2 -d '{{ images_dir }}/{{ opnsense_image_archive_file }}'
    when: opnsense_image_file_stat.stat.exists is false and opnsense_image_archive_file_stat.stat.exists is true

  - name: Upload OPNsense image file to OpenStack Glance
    openstack.cloud.image:
      ca_cert: '{{ ca_cert_path }}'
      name: '{{ opnsense_image_name }}'
      filename: '{{ images_dir }}/{{ opnsense_image_file }}'
      disk_format: raw

  - name: Download Rocky image
    ansible.builtin.get_url:
      url: '{{ rocky_image_url }}/{{ rocky_image_file }}'
      dest: '{{ images_dir }}/{{ rocky_image_file }}'
      checksum: 'sha256:{{ rocky_image_file_sha256 }}'

  - name: Upload Rocky image file to OpenStack Glance
    openstack.cloud.image:
      ca_cert: '{{ ca_cert_path }}'
      name: '{{ rocky_image_name }}'
      filename: '{{ images_dir }}/{{ rocky_image_file }}'
      disk_format: qcow2